kibot:
  version: 1

preflight:
  check_zone_fills: true
  drc: true

# Fabrication outputs
outputs:
  # Gerber files (essential for PCB manufacturing)
  - name: gerbers
    comment: "Gerber files for PCB fabrication"
    type: gerber
    options:
      output: '%f_gerbers'
    layers:
      - F.Cu
      - B.Cu
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: drills
    comment: "Drill files for PCB fabrication"
    type: excellon
    options:
      output: '%f_drills'
      # remove use_aux_origin if Kibot warns about it

  - name: pos
    comment: "Pick and place file"
    type: position
    options:
      output: '%f_pos_%i.csv'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: true

  - name: bom
    comment: "Bill of Materials"
    type: bom
    options:
      output: '%f_bom.csv'
      format: CSV
      columns:
        - Reference
        - Value
        - Footprint
        - Footprint Lib
        - Footprint X
        - Footprint Y
        - Footprint Rot
        - Footprint Side

  - name: schematic_pdf
    comment: "PDF schematic"
    type: pdf_sch_print
    options:
      output: '%f_schematic.pdf'
      frame: true
      all_pages: true

  - name: layout_pdf
    comment: "PDF layout"
    type: pcb_print
    options:
      output: '%f_layout.pdf'
      format: PDF
      scaling: 1
      pages:
        - { name: board }

  - name: 3d_model
    comment: "3D STEP model"
    type: export_3d
    options:
      output: '%f_3d.step'

  - name: ipc2581
    comment: "IPC-2581 manufacturing data"
    type: ipc2581
    options:
      output: '%f_ipc2581.xml'