M48
; DRILL file {KiCad 9.0.5} date 2025-10-13T11:36:19+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-13T11:36:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X129.0Y-97.52
X129.0Y-138.16
X144.24Y-97.52
X144.24Y-138.16
T2
X103.0Y-73.0
X103.0Y-147.0
X147.0Y-73.0
X147.0Y-147.0
M30
