name: KiBot GitHub action

on:
  push:
    branches: [ main ]
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - "*.kicad_pro"

jobs:
  generate_outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v1.8.4
        with:
          config: config.kibot.yml
      
      # Create a clean fabrication outputs directory
      - name: Prepare fabrication outputs
        run: |
          mkdir -p fabrication_artifacts
          # Copy gerber files from the gerbers output directory
          cp -r sensor_pcb_gerbers/* fabrication_artifacts/ 2>/dev/null || true
          # Copy drill files from the drills output directory  
          cp -r sensor_pcb_drills/* fabrication_artifacts/ 2>/dev/null || true
          # Copy other important files
          cp *.csv *.pdf *.step *.xml *.html fabrication_artifacts/ 2>/dev/null || true
          
      # Upload only the clean fabrication artifacts
      - name: Upload fabrication outputs
        uses: actions/upload-artifact@v4
        with:
          name: fabrication-outputs
          path: fabrication_artifacts/
          retention-days: 30

      # List files for debugging purposes
      - name: List generated files (debug)
        run: |
          echo "=== Current directory ==="
          ls -la
          echo "=== sensor_pcb_gerbers ==="
          ls -la sensor_pcb_gerbers/ 2>/dev/null || echo "Directory not found"
          echo "=== sensor_pcb_drills ==="  
          ls -la sensor_pcb_drills/ 2>/dev/null || echo "Directory not found"

  upload_release:
    needs: generate_outputs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: fabrication-outputs
          path: ./release_artifacts
      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          body: "Automated fabrication outputs from main branch"
          files: ./release_artifacts/**
