name: KiBot GitHub action

on:
  push:
    branches: [ main ]
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - "*.kicad_pro"

jobs:
  drc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v1.8.4
        with:
          config: config.kibot.yml
  generate_outputs:
    needs: drc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v1.8.4
        with:
          config: config.kibot.yml
      
      # Create a clean fabrication outputs directory
      - name: Prepare fabrication outputs
        run: |
          mkdir -p fabrication_artifacts
          # Copy main fabrication files
          cp -r fabrication/* fabrication_artifacts/ 2>/dev/null || true
          # Copy individual gerber/drill files from root
          cp MAX31865_gerbers/* fabrication_artifacts/ 2>/dev/null || true
          cp MAX31865_drills/* fabrication_artifacts/ 2>/dev/null || true
          # Copy other important files
          cp *.csv *.pdf *.step *.xml fabrication_artifacts/ 2>/dev/null || true
          
      # Upload only the clean fabrication artifacts
      - name: Upload fabrication outputs
        uses: actions/upload-artifact@v4
        with:
          name: fabrication-outputs
          path: fabrication_artifacts/
          retention-days: 30
  upload_release:
    needs: generate_outputs
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: fabrication-outputs
          path: ./release_artifacts
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./release_artifacts/**
