name: KiBot GitHub action

on:
  push:
    branches: [ main ]
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - "*.kicad_pro"

jobs:
  drc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v1.8.4
        with:
          config: config.kibot.yml
  generate_outputs:
    needs: drc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v1.8.4
        with:
          config: config.kibot.yml
          
      # Optional: Upload generated files as artifacts
      - name: Upload fabrication outputs
        uses: actions/upload-artifact@v4
        with:
          name: fabrication-outputs
          path: |
            *.zip
            *.gerber
            *.gbr
            *.drl
            *.csv
            *.pdf
            *.step
            *.xml
  upload_release:
    needs: generate_outputs
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: fabrication-outputs
          path: ./release_artifacts
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./release_artifacts/*.zip
