name: KiBot GitHub action

on:
  push:
    branches: [ main ]
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - "*.kicad_pro"

jobs:
  drc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v1.8.4
        with:
          config: config.kibot.yml
